spring.application.name=api-gateway
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# TURN OFF discovery locator for now (to avoid confusion)
spring.cloud.gateway.discovery.locator.enabled=false

# ✅ Routes (IMPORTANT: lb:// must match Eureka serviceId)
spring.cloud.gateway.routes[0].id=product-route
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/products/**

spring.cloud.gateway.routes[1].id=order-route
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/order/**

spring.cloud.gateway.routes[2].id=inventory-route
spring.cloud.gateway.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventory/**